CC = gcc
#C compiler
CFLAGS += -std=c99 -Wall
#C compiler options
CFLAGS += -DMULTIFLUID_BASICS -DPRIMITIVE_CONSERVATIVE_CONVERT
CFLAGD  = 
#Macro definition
INCLUDE_FOLDER = include
#Inclued folder
C_SUF = .c
#Source code file suffix

include ../tools/module.mk
