CC = g++
#C compiler
CFLAGS += -std=c++20 -Wall
#C compiler options
CFLAGS += -D_Bool=bool
CFLAGD  = 
#Macro definition
INCLUDE_FOLDER = include_cpp
#Inclued folder
C_SUF = .cpp
#Source code file suffix

include ../MAKE/module.mk
