/**
 * @file  hydrocode.c
 * @brief This is a C file of the main function.
 */

/** 
 * @mainpage 1D Godunov/GRP scheme for Lagrangian/Eulerian hydrodynamics
 * @brief This is an implementation of fully explict forward Euler scheme
 *        for 1-D Euler equations of motion on Lagrangian/Eulerian coordinate.
 * @version 0.1
 *
 * @section File_directory File directory
 * <table>
 * <tr><th> data_in/  <td> Folder to store input files RHO/U/P/config.txt
 * <tr><th> data_out/ <td> Folder to store output files RHO/U/P/E/X/log.txt
 * <tr><th> doc/      <td> Code documentation generated by doxygen
 * <tr><th> src/      <td> Folder to store C source code
 * </table>
 * 
 * @section Program_structure Program structure
 * <table>
 * <tr><th> include/                   <td> Header files
 * <tr><th> file_io/                   <td> Program reads and writes files
 * <tr><th> finite_volume/             <td> finite volume scheme program
 * <tr><th> Riemann_solver/            <td> Riemann solver programs
 * <tr><th> tools/                     <td> Tool functions
 * <tr><th> hydrocode/hydrocode.c      <td> Main program
 * <tr><th> hydrocode/make.sh          <td> Bash script compiles and runs programs
 * </table>
 *
 * @section Status_code Program exit status code
 * <table>
 * <tr><th> 0  <td> EXIT_SUCCESS
 * <tr><th> 1  <td> File directory error
 * <tr><th> 2  <td> Data reading error
 * <tr><th> 3  <td> Calculation error
 * <tr><th> 4  <td> Arguments error
 * <tr><th> 5  <td> Memory error
 * </table>
 * 
 * @section Compile_environment Compile environment
 *          - Linux/Unix: gcc, glibc, MATLAB/Octave
 *            - Compile in 'src/hydrocode': Run './make.sh' command on the terminal.
 *          - Winodws: Visual Studio, MATLAB/Octave
 *            - Create a C++ Project from Existing Code in 'src/'.
 *            - Compile in 'x64/Debug' using shortcut key 'Ctrl+B' with Visual Studio.
 *
 * @section Usage_description Usage description
 *          - Input files are stored in folder '/data_in/one-dim/name_of_test_example'.
 *          - Input files may be produced by MATLAB/Octave script 'value_start.m'.
 *          - Description of configuration file 'config.txt' refers to 'doc/config.csv'.
 *          - Run program:
 *            - Linux/Unix: Run 'hydrocode.out name_of_test_example order coordinate' command on the terminal. \n
 *                          e.g. 'hydrocode.out GRP_Book_6_1 2 LAG' (second-order Lagrangian GRP scheme).
 *                          - order: Order of Godunov/GRP numerical scheme (= 1 or 2).
 *                          - coordinate: Lagrangian/Eulerian coordinate framework (= LAG or EUL).
 *            - Windows: Run 'hydrocode.exe name_of_test_example order coordinate' command on the terminal. \n
 *                       [Debug] Project -> Properties -> Configuration Properties -> Debugging \n
 *             <table>
 *             <tr><th> Command Arguments <td> name_of_test_example order coordinate (e.g. 'GRP_Book_6_1 1 EUL')
 *             <tr><th> Working Directory <td> \$(SolutionDir)\$(Platform)\\\$(Configuration)\
 *             </table>
 *                       [Run] Project -> Properties -> Configuration Properties -> Linker -> System \n
 *             <table>
 *             <tr><th> Subsystem <td> 控制台 (/SUBSYSTEM:CONSOLE)
 *             </table>
 * 
 *          - Output files can be found in folder '/data_out/one-dim/'.
 *          - Output files may be visualized by MATLAB/Octave script 'value_plot.m'.
 */


#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "../include/var_struc.h"
#include "../include/file_io.h"
#include "../include/finite_volume.h"


double config[N_CONF]; //!< Initial configuration data array.

/**
 * @brief This is the main function which constructs the
 *        main structure of the Lagrangian/Eulerian hydrocode.
 * @param[in] argc: ARGument counter.
 * @param[in] argv: ARGument values.
 *            - argv[1]: Folder name of test example (input path).
 *            - argv[2]: Folder name of numerical results (output path).
 *            - argv[3]: Dimensionality (= 1).
 *            - argv[4]: Order of numerical scheme[_scheme name] (= 1[_Riemann_exact] or 2[_GRP]).
 *            - argv[5]: Lagrangian/Eulerian coordinate framework (= LAG or EUL).
 *            - argv[6,7,…]: Configuration supplement config[n]=(double)C (= n=C).
 * @return Program exit status code.
 */

#define CV_INIT_MEM(v, N)						\
    do {								\
	CV.v = (double **)malloc(N * sizeof(double *));			\
	CV.v[0] = FV0.v + 1;						\
	for(k = 1; k < N; ++k)						\
	    {								\
		CV.v[k] = (double *)malloc(m * sizeof(double));		\
		if(CV.v[k] == NULL)					\
		    {							\
			printf("NOT enough memory! %s[%d]\n", #v, k);	\
			goto return_NULL;				\
		    }							\
	    }								\
    } while (0)								\

int main(int argc, char *argv[])
{
    printf("\nTEST:\n  %s\n", argv[1]);
    printf("Test Beginning: ARGuments Counter = %d.\n", argc);

    int k;
    for(k = 1; k < N_CONF; k++)
        config[k] = INFINITY;
    
    // Set dimension.
    double dim;
    dim = atoi(argv[3]);
    if (dim != 1 && dim !=2 && dim !=3)
	{
	    printf("No appropriate dimension was entered!\n");
	    return 4;
	}
    config[0] = (double)dim;

    struct flu_var FV0; // Structural body of initial data array pointer.
    /* 
     * We read the initial data files.
     * The function initialize return a point pointing to the position
     * of a block of memory consisting (m+1) variables of type double.
     * The value of first array element of these variables is m.
     * The following m variables are the initial value.
     */
    _1D_initialize(argv[1], &FV0); 
    /* 
     * m is the number of initial value as well as the number of grids.
     * As m is frequently use to represent the number of grids,
     * we do not use the name such as num_grid here to correspond to
     * notation in the math theory.
     */
    int m = (int)FV0.RHO[0];

    char * endptr;
    int j;
    double conf_tmp;
    for (k = 6; k < argc; k++)
	{
	    errno = 0;
	    j = strtol(argv[k], &endptr, 10);
	    if (errno != ERANGE && *endptr == '=')
		{							
		    endptr++;
		    errno = 0;
		    conf_tmp = strtod(endptr, &endptr);
		    if (errno != ERANGE && *endptr == '\0')
            {
			config[j] = conf_tmp;
						printf("%3d-th configuration: %g (supplement)\n", j, conf_tmp);
        }
		    else
			printf("Configuration error in ARGument variable! ERROR 2!\n");
		}
	    else
		printf("Configuration error in ARGument variable! ERROR 1!\n");
	}
    double h = config[10], gamma = config[6];

  // The number of times steps of the fluid data stored for plotting.
  int N = 2; // (int)(config[5]) + 1;

  struct cell_var CV;
  double ** X;
  double * cpu_time;
  // Initialize arrays of fluid variables.
  CV_INIT_MEM(RHO, N);
  CV_INIT_MEM(U, N);
  CV_INIT_MEM(P, N);
  CV.E = (double**)malloc(N * sizeof(double*));
  for(k = 0; k < N; ++k)
  {
    CV.E[k] = (double *)malloc(m * sizeof(double));
    if(CV.E[k] == NULL)
    {
      printf("NOT enough memory! E[%d]\n", k);
      goto return_NULL;
    }
  }
  X = (double**)malloc(N * sizeof(double*));
  for(k = 0; k < N; ++k)
  {
    X[k] = (double *)malloc((m+1) * sizeof(double));
    if(X[k] == NULL)
    {
      printf("NOT enough memory! X[%d]\n", k);
      goto return_NULL;
    }
  }
  // Initialize the values of energy in computational cells and x-coordinate of the cell interfaces.
  for(k = 0; k < m; ++k)
      CV.E[0][k] = 0.5*CV.U[0][k]*CV.U[0][k] + CV.P[0][k]/(gamma - 1.0)/CV.RHO[0][k]; 
  for(k = 0; k <= m; ++k)
      X[0][k] = h * k;

  cpu_time = malloc(N * sizeof(double));
  if(cpu_time == NULL)
      {
	  printf("NOT enough memory! CPU_time\n");
	  goto return_NULL;
      }
      
  int order; // 1-Godunov, 2-GRP
  char * scheme;
  printf("Order_Scheme: %s\n",argv[4]);
  errno = 0;
  order = strtol(argv[4], &scheme, 10);	
  if (*scheme == '_')
      scheme++;
  else if (*scheme != '\0' || errno == ERANGE)
      {
	  printf("No order or Wrog scheme!\n");
	  goto return_NULL;
      }
  config[9] = (double)order;

  if (strcmp(argv[5],"LAG") == 0) // Use GRP/Godunov scheme to solve it on Lagrangian coordinate.
      {
	  config[8] = (double)1;
	  switch(order)
	      {
	      case 1:
		  Godunov_solver_LAG_source(m, CV, X, cpu_time);
		  break;
	      case 2:
		  GRP_solver_LAG_source(m, CV, X, cpu_time);
		  break;
	      default:
		  printf("NOT appropriate order of the scheme! The order is %d.\n", order);
		  goto return_NULL;
	      }
      }
  else if (strcmp(argv[5],"EUL") == 0) // Use GRP/Godunov scheme to solve it on Eulerian coordinate.
      {
	  config[8] = (double)0;
	  switch(order)
	      {
	      case 1:
		  Godunov_solver_EUL_source(m, CV, X, cpu_time);
		  break;
	      case 2:
		  GRP_solver_EUL_source(m, CV, X, cpu_time);
		  break;
	      default:
		  printf("NOT appropriate order of the scheme! The order is %d.\n", order);
		  goto return_NULL;
	      }
      }
  else
      {
	  printf("NOT appropriate coordinate framework! The framework is %s.\n", argv[5]);
	  goto return_NULL;
      }

  // Write the final data down.
  _1D_file_write(m, N, CV, X, cpu_time, argv[2]);

 return_NULL:
  for(k = 1; k < N; ++k)
  {
    free(CV.RHO[k]);
    free(CV.U[k]);
    free(CV.P[k]);
    free(CV.E[k]);
    free(X[k]);
    CV.RHO[k] = NULL;
    CV.U[k] = NULL;
    CV.P[k] = NULL;
    CV.E[k] = NULL;
    X[k] = NULL;
  }
  free(FV0.RHO);
  free(FV0.U);
  free(FV0.P);
  FV0.RHO = NULL;
  FV0.U = NULL;
  FV0.P = NULL;
  CV.RHO[0] = NULL;
  CV.U[0] = NULL;
  CV.P[0] = NULL;
  free(CV.E[0]);
  CV.E[0] = NULL;
  free(X[0]);
  X[0] = NULL;
  free(cpu_time);
  cpu_time = NULL;
  
  return 0;
}
