CC = gcc
#C compiler
CFLAGS += -std=c99 -Wall
#C compiler options
CFLAGS += -DMULTIFLUID_BASICS
CFLAGD  = -DRiemann_solver_exact_single=Riemann_solver_exact_Ben #-DEXACT_TANGENT_DERIVATIVE
#Macro definition
INCLUDE_FOLDER = include
#Inclued folder
C_SUF = .c
#Source code file suffix

include ../tools/module.mk
