CC = gcc
#C compiler
CFLAGS += -std=c99 -Wall
#C compiler options
CFLAGS += 
CFLAGD  = 
#Macro definition
INCLUDE_FOLDER = include_cii
#Inclued folder
C_SUF = .c
#Source code file suffix

include ../tools/module.mk
